### ISSUE TITLE
Multi-gpu parallel inference

### ISSUE THREAD

**Issue by Minami-su** [chu-tianxiang/QuIP#3]
Similar to device_map="auto" in the line model = AutoModelForCausalLM.from_pretrained(ckpt, device_map="auto")
I want to load the 'qwen 72b' 2-bit model onto 2 GPUs for inference.

**Comment by chu-tianxiang** [comment]
I would suggest using `accelerate.load_checkpoint_and_dispatch` to replace current model loading logic. Besides, current implementation uses a shared codebook for all qlinear layer, making it complicated to use multiple GPUs. Since the codebook is merely a few hundred bytes, the easiest solution is to make a copy for each qlinear layer. To sum up, replace the weight loading logic from [L586](https://github.com/chu-tianxiang/QuIP-for-all/blob/ceb75597e72a2e007694aade10b8ffe475fb2d24/quantizer.py#L586) to L621 with the following code:

```
    import copy, accelerate
    # make a copy for each linear layer's codebook
    for layer in get_layers(model, [QuantLinear]).values():
        layer.codebook = copy.deepcopy(layer.codebook)
    # loading to device
    accelerate.load_checkpoint_and_dispatch(
        model,
	checkpoint=save_folder,
        device_map="balanced",
        no_split_module_classes=quantizer.get_no_split_module_classes(model),
        dtype=torch_dtype)
```

**Comment by Minami-su** [comment]
![image](https://github.com/chu-tianxiang/QuIP-for-all/assets/76865636/4296bedd-0e34-4a7c-8cdc-ad11aeaf68a9)
![image](https://github.com/chu-tianxiang/QuIP-for-all/assets/76865636/b412bb9b-3ea2-47ad-9626-f28d7188f917)
![image](https://github.com/chu-tianxiang/QuIP-for-all/assets/76865636/ca3da5b9-450d-4331-ac4d-a5f82bac6cea)
The model is not evenly distributed; instead, there is an additional 13GB. @chu-tianxiang

**Comment by chu-tianxiang** [comment]
According to the log, you called `.cuda()` or `.to('cuda')` again after the model is loaded, which should not happen. Use the `model = load_quantized_model(quant_dir)` as it is.

**Comment by Minami-su** [comment]
> According to the log, you called `.cuda()` or `.to('cuda')` again after the model is loaded, which should not happen. Use the `model = load_quantized_model(quant_dir)` as it is.

ok,succeed.

**Comment by Minami-su** [comment]
Human:如果我们把5件衬衫放在太阳下，它需要4个小时才能变干，那么今天20件衬衫需要多长时间才能变干?<|im_end|>

Assistant: 2
Assistant:
Traceback (most recent call last):
  File "/root/autodl-tmp/QuIP-for-all/inference.py", line 52, in <module>
    response = generate(prompt)
  File "/root/autodl-tmp/QuIP-for-all/inference.py", line 13, in generate
    generate_ids = model.generate(input_ids=input_ids,
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-72B-Chat-2bit/modeling_qwen.py", line 1261, in generate
    return super().generate(
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/transformers/generation/utils.py", line 1652, in generate
    return self.sample(
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/transformers/generation/utils.py", line 2734, in sample
    outputs = self(
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-72B-Chat-2bit/modeling_qwen.py", line 1045, in forward
    transformer_outputs = self.transformer(
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-72B-Chat-2bit/modeling_qwen.py", line 893, in forward
    outputs = block(
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/accelerate/hooks.py", line 159, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/accelerate/hooks.py", line 290, in pre_forward
    return send_to_device(args, self.execution_device), send_to_device(
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/accelerate/utils/operations.py", line 160, in send_to_device
    {
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/accelerate/utils/operations.py", line 161, in <dictcomp>
    k: t if k in skip_keys else send_to_device(t, device, non_blocking=non_blocking, skip_keys=skip_keys)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/accelerate/utils/operations.py", line 151, in send_to_device
    return honor_type(
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/accelerate/utils/operations.py", line 83, in honor_type
    return type(obj)(generator)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/accelerate/utils/operations.py", line 152, in <genexpr>
    tensor, (send_to_device(t, device, non_blocking=non_blocking, skip_keys=skip_keys) for t in tensor)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/accelerate/utils/operations.py", line 151, in send_to_device
    return honor_type(
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/accelerate/utils/operations.py", line 83, in honor_type
    return type(obj)(generator)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/accelerate/utils/operations.py", line 152, in <genexpr>
    tensor, (send_to_device(t, device, non_blocking=non_blocking, skip_keys=skip_keys) for t in tensor)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/accelerate/utils/operations.py", line 167, in send_to_device
    return tensor.to(device, non_blocking=non_blocking)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

The strange thing is, it's just that the problem is different, one normal and one wrong
![image](https://github.com/chu-tianxiang/QuIP-for-all/assets/76865636/707591e2-f748-4528-a15b-7a0cd7bb555a)


![image](https://github.com/chu-tianxiang/QuIP-for-all/assets/76865636/95e0748f-423c-4f4a-87a5-b79f54c58020)

**Comment by Minami-su** [comment]
inference code:
```
from transformers import AutoTokenizer
from quantizer import load_quantized_model
import torch
quant_dir = "Qwen-72B-Chat-2bit"

model = load_quantized_model(quant_dir,trust_remote_code=True)#,torch_dtype=torch.float16
tokenizer = AutoTokenizer.from_pretrained(quant_dir,trust_remote_code=True)
def generate(prompt):
    print("1",prompt,"2")
    name=prompt.split("\n")[-1]
    print(name)
    input_ids = tokenizer(prompt, return_tensors="pt").input_ids.cuda()
    generate_ids = model.generate(input_ids=input_ids,
    max_length=500,
    #  do_sample = True, 
    # eos_token_id=tokenizer.eos_token_id )
    num_beams=1,
    do_sample=True, top_p=0.9, temperature=0.95, repetition_penalty=1.05,eos_token_id=tokenizer.eod_id, 
            bos_token_id=tokenizer.im_start_id, 
            pad_token_id=tokenizer.eod_id)
    output = tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]#
    response = output.split(name)[-1]
    print(output)
   # print("1",response,"2")
    return response

device = torch.device('cuda')
print(tokenizer.encode("</s>"))
history=[]
max_history_len=12
rating="0"
while True:
    text=input("user:")
    text=f"Human:{text}<|im_end|>\n"
    #input_text = ""
    input_text="你是一个中文ai助手，所有的回复都以中文的形式回答结束回答时一定要以<|im_end|>为结尾\n"
    for history_id, history_utr in enumerate(history[-max_history_len:]):
        input_text = input_text + history_utr + '\n'
    prompt = input_text+"Assistant:"
    prompt =prompt.strip()
    response = generate(prompt)
    response=response.strip()
    response="Assistant:"+response+"<|im_end|>"
    #response="伊蕾娜: "+response
    print("1",response,"2")
    history.append(response)
```

**Comment by Minami-su** [comment]
```
Traceback (most recent call last):
  File "/root/autodl-tmp/QuIP-for-all/inference.py", line 52, in <module>
    response = generate(prompt)
  File "/root/autodl-tmp/QuIP-for-all/inference.py", line 13, in generate
    generate_ids = model.generate(input_ids=input_ids,
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-72B-Chat-2bit/modeling_qwen.py", line 1261, in generate
    return super().generate(
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/transformers/generation/utils.py", line 1652, in generate
    return self.sample(
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/transformers/generation/utils.py", line 2734, in sample
    outputs = self(
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-72B-Chat-2bit/modeling_qwen.py", line 1045, in forward
    transformer_outputs = self.transformer(
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-72B-Chat-2bit/modeling_qwen.py", line 893, in forward
    outputs = block(
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-72B-Chat-2bit/modeling_qwen.py", line 612, in forward
    attn_outputs = self.attn(
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-72B-Chat-2bit/modeling_qwen.py", line 416, in forward
    mixed_x_layer = self.c_attn(hidden_states)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/autodl-tmp/QuIP-for-all/qlinear.py", line 98, in forward
    out = matmul_hadU_cuda(out, self.had_right, self.K_right,
  File "/root/autodl-tmp/QuIP-for-all/quant.py", line 98, in matmul_hadU_cuda
    input = hadK @ input
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmStridedBatchedExFix( handle, opa, opb, m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`
```

**Comment by chu-tianxiang** [comment]
I fixed a bug in the kernel file, not sure if it's relevant to your problem. 
I tested with following simpler script on 2 GPUs, still the model has a strong tendency to generate English output.  I'll try quantize another one with bilingual texts.

```python
import torch
from transformers import AutoTokenizer, GenerationConfig
from quantizer import load_quantized_model

quant_dir = "Qwen-72B-Chat-2bit"

model = load_quantized_model(quant_dir,trust_remote_code=True,torch_dtype=torch.bfloat16)
tokenizer = AutoTokenizer.from_pretrained(quant_dir,trust_remote_code=True)
model.generation_config = GenerationConfig.from_pretrained(quant_dir)

history = []
system = "你是一个中文ai助手，所有的回复都以中文的形式回答结束回答时一定要以<|im_end|>为结尾"
while True:
    text = input("User:")
    response, history = model.chat(tokenizer, text, history=history, system=system)
    print("Assistant:", response)
```

```
User:你是谁
Assistant:  我是通义千问，由阿里云开发的AI助手。我可以回答各种问题、提供信息和与用户进行对话。有什么我可以帮助你的吗？
User:如果我们把5件衬衫放在太阳下，它需要4个小时才能变干，那么今天20件衬衫需要多长时间才能变干
Assistant:  根据您提供的信息，将5件衬衫放在太阳下需要4 hours to dry. If we double the number of shirts, it will take twice as long for them to dry. Therefore, if you have 20 shirts, it will take 8 hours for them to dry under the sun.
```

**Comment by Minami-su** [comment]
> I fixed a bug in the kernel file, not sure if it's relevant to your problem. I tested with following simpler script on 2 GPUs, still the model has a strong tendency to generate English output. I'll try quantize another one with bilingual texts.
> 
> ```python
> import torch
> from transformers import AutoTokenizer, GenerationConfig
> from quantizer import load_quantized_model
> 
> quant_dir = "Qwen-72B-Chat-2bit"
> 
> model = load_quantized_model(quant_dir,trust_remote_code=True,torch_dtype=torch.bfloat16)
> tokenizer = AutoTokenizer.from_pretrained(quant_dir,trust_remote_code=True)
> model.generation_config = GenerationConfig.from_pretrained(quant_dir)
> 
> history = []
> system = "你是一个中文ai助手，所有的回复都以中文的形式回答结束回答时一定要以<|im_end|>为结尾"
> while True:
>     text = input("User:")
>     response, history = model.chat(tokenizer, text, history=history, system=system)
>     print("Assistant:", response)
> ```
> 
> ```
> User:你是谁
> Assistant:  我是通义千问，由阿里云开发的AI助手。我可以回答各种问题、提供信息和与用户进行对话。有什么我可以帮助你的吗？
> User:如果我们把5件衬衫放在太阳下，它需要4个小时才能变干，那么今天20件衬衫需要多长时间才能变干
> Assistant:  根据您提供的信息，将5件衬衫放在太阳下需要4 hours to dry. If we double the number of shirts, it will take twice as long for them to dry. Therefore, if you have 20 shirts, it will take 8 hours for them to dry under the sun.
> ```
ok,succeed.
