### ISSUE TITLE
windows无法安装quiptools-cuda

### ISSUE THREAD

**Issue by xldistance** [chu-tianxiang/QuIP#4]
```
[2/3] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc --generate-dependencies-with-compile --dependency-output E:\Langchain-Chatchat\quip_cuda\build\temp.win-amd64-cpython-310\Release\origin_order.obj.d -std=c++17 --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /wd4624 -Xcompiler /wd4067 -Xcompiler /wd4068 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IE:\Langchain-Chatchat\glut\lib\site-packages\torch\include -IE:\Langchain-Chatchat\glut\lib\site-packages\torch\include\torch\csrc\api\include -IE:\Langchain-Chatchat\glut\lib\site-packages\torch\include\TH -IE:\Langchain-Chatchat\glut\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -IE:\Langchain-Chatchat\glut\include -IE:\Langchain-Chatchat\glut\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -c E:\Langchain-Chatchat\quip_cuda\origin_order.cu -o E:\Langchain-Chatchat\quip_cuda\build\temp.win-amd64-cpython-310\Release\origin_order.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -g -Xcompiler -rdynamic -lineinfo -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=quiptools_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
      FAILED: E:/Langchain-Chatchat/quip_cuda/build/temp.win-amd64-cpython-310/Release/origin_order.obj
      C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc --generate-dependencies-with-compile --dependency-output E:\Langchain-Chatchat\quip_cuda\build\temp.win-amd64-cpython-310\Release\origin_order.obj.d -std=c++17 --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /wd4624 -Xcompiler /wd4067 -Xcompiler /wd4068 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IE:\Langchain-Chatchat\glut\lib\site-packages\torch\include -IE:\Langchain-Chatchat\glut\lib\site-packages\torch\include\torch\csrc\api\include -IE:\Langchain-Chatchat\glut\lib\site-packages\torch\include\TH -IE:\Langchain-Chatchat\glut\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -IE:\Langchain-Chatchat\glut\include -IE:\Langchain-Chatchat\glut\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -c E:\Langchain-Chatchat\quip_cuda\origin_order.cu -o E:\Langchain-Chatchat\quip_cuda\build\temp.win-amd64-cpython-310\Release\origin_order.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -g -Xcompiler -rdynamic -lineinfo -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=quiptools_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
      cl: 命令行 warning D9002 :忽略未知选项“-rdynamic”
      origin_order.cu
      cl: 命令行 warning D9002 :忽略未知选项“-rdynamic”
      origin_order.cu
      E:\Langchain-Chatchat\quip_cuda\origin_order.cu(41): warning #177-D: variable "KTilesPerWarp" was declared but never referenced
        constexpr int32_t KTilesPerWarp = 8;
                          ^

      Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"



      origin_order.cu

      cl: 命令行 warning D9002 :忽略未知选项“-rdynamic”

      tmpxft_00003690_00000000-7_origin_order.cudafe1.cpp

      C:\Users\XLDIST~1\AppData\Local\Temp\tmpxft_00003690_00000000-7_origin_order.cudafe1.cpp: fatal error C1041: 无法打开程序数据库“E:\Langchain-Chatchat\quip_cuda\build\temp.win-amd64-cpython-310\Release\vc140.pdb”；如果要将多个 CL.EXE 写入同一个 .PDB 文件，请使用 /FS

      [3/3] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc --generate-dependencies-with-compile --dependency-output E:\Langchain-Chatchat\quip_cuda\build\temp.win-amd64-cpython-310\Release\e8p_gemv.obj.d -std=c++17 --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /wd4624 -Xcompiler /wd4067 -Xcompiler /wd4068 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IE:\Langchain-Chatchat\glut\lib\site-packages\torch\include -IE:\Langchain-Chatchat\glut\lib\site-packages\torch\include\torch\csrc\api\include -IE:\Langchain-Chatchat\glut\lib\site-packages\torch\include\TH -IE:\Langchain-Chatchat\glut\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -IE:\Langchain-Chatchat\glut\include -IE:\Langchain-Chatchat\glut\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -c E:\Langchain-Chatchat\quip_cuda\e8p_gemv.cu -o E:\Langchain-Chatchat\quip_cuda\build\temp.win-amd64-cpython-310\Release\e8p_gemv.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -g -Xcompiler -rdynamic -lineinfo -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=quiptools_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
      cl: 命令行 warning D9002 :忽略未知选项“-rdynamic”
      e8p_gemv.cu
      cl: 命令行 warning D9002 :忽略未知选项“-rdynamic”
      e8p_gemv.cu
      E:\Langchain-Chatchat\quip_cuda\e8p_gemv.cu(85): warning #177-D: variable "shared_weights" was declared but never referenced
            __declspec(__shared__) uint2 shared_weights[1024*2];
                                         ^



      Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"



      e8p_gemv.cu

      cl: 命令行 warning D9002 :忽略未知选项“-rdynamic”

      tmpxft_0000ca30_00000000-7_e8p_gemv.cudafe1.cpp

      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "E:\Langchain-Chatchat\glut\lib\site-packages\torch\utils\cpp_extension.py", line 2100, in _run_ninja_build
          subprocess.run(
        File "E:\Langchain-Chatchat\glut\lib\subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "E:\Langchain-Chatchat\quip_cuda\setup.py", line 4, in <module>
          setup(name='quiptools_cuda',
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "E:\Langchain-Chatchat\glut\lib\site-packages\wheel\bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "E:\Langchain-Chatchat\glut\lib\site-packages\torch\utils\cpp_extension.py", line 873, in build_extensions
          build_ext.build_extensions(self)
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "E:\Langchain-Chatchat\glut\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "E:\Langchain-Chatchat\glut\lib\site-packages\torch\utils\cpp_extension.py", line 845, in win_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "E:\Langchain-Chatchat\glut\lib\site-packages\torch\utils\cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "E:\Langchain-Chatchat\glut\lib\site-packages\torch\utils\cpp_extension.py", line 2116, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for quiptools-cuda
  Running setup.py clean for quiptools-cuda
Failed to build quiptools-cuda
ERROR: Could not build wheels for quiptools-cuda, which is required to install pyproject.toml-based projects
```

**Comment by xldistance** [comment]
把quip_cuda里面的setup.py修改如下好了
```
cmdclass={'build_ext': cpp_extension.BuildExtension.with_options(use_ninja=False)
```
